[theme.light]
primaryColor="rgb(255, 140, 24)"

[theme.light.sidebar]
primaryColor="rgb(255, 140, 24)"

[theme.dark]
primaryColor="rgb(255, 140, 24)"
showWidgetBorder=true

[theme.dark.sidebar]
primaryColor="rgb(255, 140, 24)"
